Traceback (most recent call last):
  File "/Users/fynnfu/PycharmProjects/TelegramBots/ChatGPT/views.py", line 674, in handle_messages
    Bot.edit_message_text(chat_id=message.from_user.id,
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/telebot/__init__.py", line 3839, in edit_message_text
    result = apihelper.edit_message_text(self.token, text, chat_id, message_id, inline_message_id, parse_mode,
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/telebot/apihelper.py", line 1327, in edit_message_text
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/telebot/apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/telebot/apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Character '.' is reserved and must be escaped with the preceding '\'
